// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFH3vqa57XSehcaMxdeEh2X08VfLioxeQ',
    appId: '1:449941346558:web:8337fa70aa28b820c3adaf',
    messagingSenderId: '449941346558',
    projectId: 'blocapplcation',
    authDomain: 'blocapplcation.firebaseapp.com',
    storageBucket: 'blocapplcation.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvJzQJdCkN163-0nYaU-Gh0yWOQ3JoMRc',
    appId: '1:449941346558:android:dc6a333cc6111208c3adaf',
    messagingSenderId: '449941346558',
    projectId: 'blocapplcation',
    storageBucket: 'blocapplcation.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4HpK6wWSad9VRwfoUgImRZ_er5Eza_AA',
    appId: '1:449941346558:ios:347b18cb6f89e21bc3adaf',
    messagingSenderId: '449941346558',
    projectId: 'blocapplcation',
    storageBucket: 'blocapplcation.firebasestorage.app',
    iosBundleId: 'com.example.blocapplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4HpK6wWSad9VRwfoUgImRZ_er5Eza_AA',
    appId: '1:449941346558:ios:347b18cb6f89e21bc3adaf',
    messagingSenderId: '449941346558',
    projectId: 'blocapplcation',
    storageBucket: 'blocapplcation.firebasestorage.app',
    iosBundleId: 'com.example.blocapplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFH3vqa57XSehcaMxdeEh2X08VfLioxeQ',
    appId: '1:449941346558:web:19f53d52f62143e1c3adaf',
    messagingSenderId: '449941346558',
    projectId: 'blocapplcation',
    authDomain: 'blocapplcation.firebaseapp.com',
    storageBucket: 'blocapplcation.firebasestorage.app',
  );
}
